import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-stone-800 text-white py-4">
          <ul className="flex gap-3 container mx-auto">
            <li>
              <Link href='/'>
                Home
              </Link>
            </li>
            <li>
              <Link href='/about'>
                About
              </Link>
            </li>
            <li>
              <Link href='/pokemon'>
                Pokemon
              </Link>
            </li>
          </ul>
        </nav>
        <div className="container mx-auto p-5">

        {children}
        </div>
      </body>
    </html>
  );
}
